In [1]:
1 * 3

3

In [2]:
def kali(a):
    print(a*3)
a = kali (3)

9


In [4]:
print(a)

None


In [5]:
def kali(a,b):
    return a*b
print(kali(2,3))


6


In [7]:
x = kali(3,4)
y = kali(5,6)
z = kali(x,y)
print(z)

360


In [8]:
def str_joiner(a,b):
    return a + b

In [9]:
str_joiner('ayam', 'burung')

'ayamburung'

In [26]:
def str_joiner(a,b,c):
    a = a.capitalize()
    b = b.capitalize()
    c = c.capitalize()
    return a + b + c
str_joiner('saya ', 'mau ', 'makan ') [::-1]


' nakaM uaM ayaS'

In [28]:
total= 20
def function_a(a,b):
    total = a+b
    return total
print(total)
print(function_a(2,5))

20
7


In [44]:
mylist = [31,21,2,56,77,23,12,11,19,20,31,35,17]

def func(a):
    nGenap = 0
    nGanjil = 0
    sumGenap = 0
    sumGanjil = 0
    for i in a:
        if i % 2 ==0:
            nGenap += 1
            sumGenap += 1
        else:
            nGanjil += 1
            sumGanjil += i
    print ('n angka ganjil adalah = ' + str(nganjil))
    print ('n angka genap adalah = ' + str(nGenap))
    print ('n sum angka ganjil adalah = ' + str(sumGanjil))
    print ('n sum angka ganjil adalah = ' + str(sumGenap))

In [48]:
def printinfo(name,age=21):
    print('Name : ',name)
    print('Age : ',age)
printinfo('Isma')

Name :  Isma
Age :  21


In [49]:
def printinfo(x, *vartuple):
    print('output is :')
    print(x)
    print(vartuple)

In [51]:
printinfo(2,5,6,7,'isma',0)

output is :
2
(5, 6, 7, 'isma', 0)


Lambda

In [53]:
def sum(x,y):
    return x + y
print(sum(3,8))

11


In [56]:
perkalian = lambda x,y:x*y
print(perkalian(5,6))

30


modules

In [58]:
import numpy as np
np.sqrt(9)

3.0

In [59]:
dir()

['In',
 'Out',
 '_',
 '_1',
 '_14',
 '_15',
 '_17',
 '_25',
 '_26',
 '_30',
 '_57',
 '_58',
 '_9',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i13',
 '_i14',
 '_i15',
 '_i16',
 '_i17',
 '_i18',
 '_i19',
 '_i2',
 '_i20',
 '_i21',
 '_i22',
 '_i23',
 '_i24',
 '_i25',
 '_i26',
 '_i27',
 '_i28',
 '_i29',
 '_i3',
 '_i30',
 '_i31',
 '_i32',
 '_i33',
 '_i34',
 '_i35',
 '_i36',
 '_i37',
 '_i38',
 '_i39',
 '_i4',
 '_i40',
 '_i41',
 '_i42',
 '_i43',
 '_i44',
 '_i45',
 '_i46',
 '_i47',
 '_i48',
 '_i49',
 '_i5',
 '_i50',
 '_i51',
 '_i52',
 '_i53',
 '_i54',
 '_i55',
 '_i56',
 '_i57',
 '_i58',
 '_i59',
 '_i6',
 '_i7',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'a',
 'exit',
 'func',
 'function_a',
 'get_ipython',
 'kali',
 'mylist',
 'np',
 'perkalian',
 'printinfo',
 'quit',
 'str_joiner',
 'sum',
 'total',
 'x',
 'y',
 'z']

In [61]:
np.__file__

'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'

In [62]:
import matplotlib.pyplot as plt

In [3]:
import numpy as np

In [5]:
array_3 = np.array([[1,2,3,4]])
array_4 = np.array([[5,6,7,8]])
np.vstack([array_3,array_4])
print(np.hstack([array_3,array_4]))

[[1 2 3 4 5 6 7 8]]


In [4]:
array_5 = np.array([1,2,3,4])
array_6 = np.array([5,6,7,8])
np.hstack([array_5,array_6])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
np.append(array_3,[5,6,7,8])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
#np.newaxis
array_4 = np.array([4,5,6])
array_4[np.newaxis]
print(array_4[:,np.newaxis].shape)

(3, 1)


In [8]:
#np.expand_dims
array_7 = np.array([3,4,5,6,7,8,9])
array_8 = np.expand_dims(array_7,axis=1)
array_9 = np.expand_dims(array_7,axis=0)
print(array_8)
print(array_8.shape)
print(array_9)
print(array_9.shape)

[[3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(7, 1)
[[3 4 5 6 7 8 9]]
(1, 7)


Operasi matematika pada array sifatnya broadcast

In [9]:
array_7 = np.array([3,4,5,6,7,8,9])
array_7*2

array([ 6,  8, 10, 12, 14, 16, 18])

In [10]:
array_10 = np.array([[1,2,3],[4,5,6]])
array_10-4

array([[-3, -2, -1],
       [ 0,  1,  2]])

Filtering Array

In [11]:
array_7 = np.array([3,4,5,6,7,8,9])
print(array_7[array_7>5])
print(array_7[array_7==8])
print(array_7[array_7<=4])

[6 7 8 9]
[8]
[3 4]


In [12]:
array_11 = np.array([[3,5,7],[8,9,10],[-1,-2,-3]])
array_11.shape
print(array_11[array_11>5])

[ 7  8  9 10]


Hstack, Vstack, hsplit, vsplit

In [13]:
#stack
array_14 = np.array([3,4,5,6,7])
array_15 = np.array([7,8,9,10,11])
print('Stack secara Vertikal')
print(np.vstack([array_14,array_15]))
print('Stack secara Horizontal')
print(np.hstack([array_14,array_15]))

Stack secara Vertikal
[[ 3  4  5  6  7]
 [ 7  8  9 10 11]]
Stack secara Horizontal
[ 3  4  5  6  7  7  8  9 10 11]


In [14]:
#hsplit
array_16 = np.array([3,4,5,6,7,8])
array_split = np.hsplit(array_16,2)
(array_split)

[array([3, 4, 5]), array([6, 7, 8])]

In [15]:
#vsplit
array_19 = np.array([[1,2,3,4],[4,5,6,7]])
print(array_19.shape)
print('Horizontal Split')
print(np.hsplit(array_19,2))
print('Vertical Split')
print(np.vsplit(array_19,2))

(2, 4)
Horizontal Split
[array([[1, 2],
       [4, 5]]), array([[3, 4],
       [6, 7]])]
Vertical Split
[array([[1, 2, 3, 4]]), array([[4, 5, 6, 7]])]


In [16]:
#vsplit
array_19 = np.array([[1,2,3,4,5,6],[4,5,6,7,5,6]])
print(array_19.shape)
print('Horizontal Split')
print(np.hsplit(array_19,3))
print('Vertical Split')
print(np.vsplit(array_19,3))

(2, 6)
Horizontal Split
[array([[1, 2],
       [4, 5]]), array([[3, 4],
       [6, 7]]), array([[5, 6],
       [5, 6]])]
Vertical Split


ValueError: array split does not result in an equal division

Operasi Aritmatika antar 2 array

In [17]:
array_a = np.array([1,2,3])
array_b = np.array([3,4,5])
print(array_a+array_b)

[4 6 8]


In [18]:
array_c = np.array([[1,2,3],[4,5,6]])
array_d = np.array([[6,7,8],[9,10,11]])
print(array_c-array_d)

[[-5 -5 -5]
 [-5 -5 -5]]


In [19]:
array_a = np.array([1,2,3])
array_b = np.array([3,4,5])
array_c = np.array([[1,2,3],[4,5,6]])
array_d = np.array([[6,7,8],[9,10,11]])
print(array_a.sum())
print(array_c.sum())
print(array_c.sum(axis=0))

6
21
[5 7 9]


In [20]:
array_c = np.array([[1,2,3],[4,5,6]])
print(array_c)
print(array_c.sum(axis=0))
print(array_c.sum(axis=1))

[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]


In [21]:
array_a = np.array([1,2,3])
array_b = np.array([3,4,5])
array_c = np.array([[5,2,3],[4,5,6]])
print(array_a.max())
print(array_c.max())
print(array_c)
print(array_c.max(axis=0))
print(array_c.min(axis=0))

3
6
[[5 2 3]
 [4 5 6]]
[5 5 6]
[4 2 3]


Transposing

In [22]:
array_c = np.array([[5,2,3],[4,5,6]])
print(array_c)
print(array_c.shape)

[[5 2 3]
 [4 5 6]]
(2, 3)


In [23]:
print(array_c.T)
print(array_c.T.shape)

[[5 4]
 [2 5]
 [3 6]]
(3, 2)


In [24]:
array_d = np.array([[1,2,3,4,5],[4,5,6,7,8],[7,8,9,10,11]])
print(array_d)
print(array_d.shape)

[[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]]
(3, 5)


In [25]:
array_d = np.array([[1,2,3,4,5],[4,5,6,7,8],[7,8,9,10,11]])
print(array_d.T)
print(array_d.T.shape)

[[ 1  4  7]
 [ 2  5  8]
 [ 3  6  9]
 [ 4  7 10]
 [ 5  8 11]]
(5, 3)


In [26]:
array_random = np.random.random([3,2])*100
print(array_random)

[[37.02038507 73.43158963]
 [ 4.94380346 38.71606096]
 [96.74774542 96.62022005]]


In [27]:
array_random = np.random.random([3,2,3])*100
print(array_random)
print(array_random.flatten())

[[[76.90521794 47.29505192 96.50635318]
  [49.65126646 12.25938185  4.33879863]]

 [[ 1.82577808  1.74154061 91.79032444]
  [40.53791897 86.6020948  38.96445993]]

 [[51.43067552 13.50171555 71.41039116]
  [23.81007119  4.59295453 80.09663373]]]
[76.90521794 47.29505192 96.50635318 49.65126646 12.25938185  4.33879863
  1.82577808  1.74154061 91.79032444 40.53791897 86.6020948  38.96445993
 51.43067552 13.50171555 71.41039116 23.81007119  4.59295453 80.09663373]


Numpy Math Formulas

In [28]:
array_random = np.random.random([3,2])*100
print(array_random)
np.sum(array_random)

[[18.19678992 91.06219141]
 [83.09369693 19.30662628]
 [56.42905116 60.52059029]]


328.60894598762974

In [30]:
np.square(9)


81

In [31]:
np.sqrt(9)


3.0

In [32]:
a = np.log(1000000)


In [33]:
print(a)


13.815510557964274


In [34]:
np.exp(a)

999999.9999999995

In [35]:
np.empty((2,2))

array([[0.e+000, 1.e-323],
       [2.e-323, 3.e-323]])

In [36]:
np.arange(0,7,2)

array([0, 2, 4, 6])

In [37]:
a = np.array([1,2,3,4])

In [38]:
a[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4]])